# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Prefer single quotes when possible
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'

# Do not require space inside array brackets
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Always require a final newline
Layout/TrailingEmptyLines:
  EnforcedStyle: final_newline

# Ensure files end with a newline
Layout/EndOfLine:
  EnforcedStyle: lf

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
